<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AppMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('app_menus')->truncate();

        $records = [
            [
                'menu_id' => 1,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Attendance',
                'menu_icon' => 'assets/images/attendance.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/Attendance',
                'menu_group' => 'Attendance',
                'menu_sequence' => '50',
                'menu_description' => 'Track your work hours',
            ],
            [
                'menu_id' => 2,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Calendar',
                'menu_icon' => 'assets/images/attendancereport.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/AttendanceCalendar',
                'menu_group' => 'Attendance',
                'menu_sequence' => '9',
                'menu_description' => 'View holidays & events',
            ],
            [
                'menu_id' => 3,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Gate Pass',
                'menu_icon' => 'assets/images/gatepass.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/GatePassList',
                'menu_group' => 'Requests',
                'menu_sequence' => '16',
                'menu_description' => 'Request entry or exit',
            ],
            [
                'menu_id' => 4,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Missed Punch',
                'menu_icon' => 'assets/images/misPunch.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/MisPunchList',
                'menu_group' => 'Requests',
                'menu_sequence' => '20',
                'menu_description' => 'Request punch correction',
            ],
            [
                'menu_id' => 5,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Leave',
                'menu_icon' => 'assets/images/leaveapplication.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/LeaveApplications',
                'menu_group' => 'Requests',
                'menu_sequence' => '17',
                'menu_description' => 'Apply & Manage leave',
            ],
            [
                'menu_id' => 6,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Leave Balance',
                'menu_icon' => 'assets/images/icons8-doughnut-chart-50.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/LeaveBalance',
                'menu_group' => 'Requests',
                'menu_sequence' => '18',
                'menu_description' => 'Check available blanace',
            ],
            [
                'menu_id' => 7,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'QR Reader',
                'menu_icon' => 'assets/images/scan-code.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/QRScanner',
                'menu_group' => 'Attendance',
                'menu_sequence' => '10',
                'menu_description' => 'Scan to mark attandance',
            ],
            [
                'menu_id' => 8,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'TA/DA',
                'menu_icon' => 'assets/images/expensesnew.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/EmployeeTADAScreen',
                'menu_group' => 'Travel',
                'menu_sequence' => '21',
                'menu_description' => 'Submit your travel claims',
            ],
            [
                'menu_id' => 9,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Travel Advance',
                'menu_icon' => 'assets/images/bonus.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/AdvanceApprovalList',
                'menu_group' => 'Approval',
                'menu_sequence' => '8',
                'menu_description' => 'Manage travel advance requests',
            ],
            [
                'menu_id' => 10,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'TA/DA',
                'menu_icon' => 'assets/images/expensesnew.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/TadaApprovalList',
                'menu_group' => 'Approval',
                'menu_sequence' => '7',
                'menu_description' => 'Manage TA/DA requests',
            ],
            [
                'menu_id' => 11,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Leave',
                'menu_icon' => 'assets/images/leavemanagement.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/LeaveApprovalList',
                'menu_group' => 'Approval',
                'menu_sequence' => '3',
                'menu_description' => 'Manage leave requests',
            ],
            [
                'menu_id' => 12,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Missed Punch',
                'menu_icon' => 'assets/images/misPunch.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/MissedPunchApprovalList',
                'menu_group' => 'Approval',
                'menu_sequence' => '5',
                'menu_description' => 'Manage correction requests',
            ],
            [
                'menu_id' => 13,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Gate Pass',
                'menu_icon' => 'assets/images/gatepass.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/GetPassApprovalList',
                'menu_group' => 'Approval',
                'menu_sequence' => '2',
                'menu_description' => 'Manage movement requests',
            ],
            [
                'menu_id' => 14,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'View Eligibility',
                'menu_icon' => null,
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/EligibilityPage',
                'menu_group' => 'Travel',
                'menu_sequence' => '22',
                'menu_description' => 'View eligible limits',
            ],
            [
                'menu_id' => 15,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'My Profile',
                'menu_icon' => '0xe491',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/ProfileScreen',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '1',
                'menu_description' => 'View and manage your profile',
            ],
            [
                'menu_id' => 16,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Holiday',
                'menu_icon' => '0xf104',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/HolidayListPage',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '2',
                'menu_description' => 'Check company holiday schedule',
            ],
            [
                'menu_id' => 18,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Privacy Policy',
                'menu_icon' => '0xf2d0',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/PrivacyPolicyPage',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '6',
                'menu_description' => 'Information about our privacy policy',
            ],
            [
                'menu_id' => 19,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'My Team',
                'menu_icon' => '0xe2eb',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/EmployeeSummaryWidget',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '3',
                'menu_description' => 'Employee information at a glance',
            ],
            [
                'menu_id' => 20,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Payslip',
                'menu_icon' => 'assets/images/payslip.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/PayslipListPage',
                'menu_group' => 'Payroll',
                'menu_sequence' => '15',
                'menu_description' => 'View and download salary payslips',
            ],
            [
                'menu_id' => 21,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Loan/Advance',
                'menu_icon' => 'assets/images/requestAd.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/RequestAdvanceListPage',
                'menu_group' => 'Requests',
                'menu_sequence' => '19',
                'menu_description' => 'View all advance payment requests',
            ],
            [
                'menu_id' => 24,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Regulatory Doc',
                'menu_icon' => 'assets/images/regulatory.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/BusinessDocumentsScreen',
                'menu_group' => 'General',
                'menu_sequence' => '14',
                'menu_description' => 'Manage compliance documents',
            ],
            [
                'menu_id' => 25,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Change Password',
                'menu_icon' => '0xe47a',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/ChangePassword',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '4',
                'menu_description' => 'Change your password for security',
            ],
            [
                'menu_id' => 26,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Help & Feedback',
                'menu_icon' => '0xf04f',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/FeedbackScreen',
                'menu_group' => 'AppDrawer',
                'menu_sequence' => '5',
                'menu_description' => 'Support and guidance for users',
            ],
            [
                'menu_id' => 27,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Enroll Face',
                'menu_icon' => 'assets/images/rg_face.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/AllEmployee',
                'menu_group' => 'General',
                'menu_sequence' => '12',
                'menu_description' => 'Enroll your face for verification',
            ],
            [
                'menu_id' => 28,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Announcement',
                'menu_icon' => 'assets/images/announcement.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/SendAnnouncementList',
                'menu_group' => 'General',
                'menu_sequence' => '11',
                'menu_description' => 'Send updates to all users',
            ],
            [
                'menu_id' => 29,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Comp-Off',
                'menu_icon' => 'assets/images/comp-off.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/CompOffList',
                'menu_group' => 'Approval',
                'menu_sequence' => '1',
                'menu_description' => 'Compensatory leave for extra work',
            ],
            [
                'menu_id' => 30,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Loan/Advance',
                'menu_icon' => 'assets/images/requestAd.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/LoanAdvanceApproval',
                'menu_group' => 'Approval',
                'menu_sequence' => '4',
                'menu_description' => 'Manage loan and advance approvals',
            ],
            [
                'menu_id' => 31,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Event & Gallery',
                'menu_icon' => 'assets/images/event.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/CreateEventGalleryList',
                'menu_group' => 'General',
                'menu_sequence' => '13',
                'menu_description' => 'Support and guidance for users',
            ],
            [
                'menu_id' => 32,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Overtime',
                'menu_icon' => 'assets/images/over_time.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/OverTimeApprovalPage',
                'menu_group' => 'Approval',
                'menu_sequence' => '6',
                'menu_description' => 'Record extra working hours',
            ],
            [
                'menu_id' => 33,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Resignation',
                'menu_icon' => 'assets/images/resignation.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/ResignationList',
                'menu_group' => 'Requests',
                'menu_sequence' => '10',
                'menu_description' => 'Resignation request',
            ],
            [
                'menu_id' => 34,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Out Door',
                'menu_icon' => 'assets/images/out_door.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/OutDoorPage',
                'menu_group' => 'Requests',
                'menu_sequence' => '9',
                'menu_description' => 'Out door request',
            ],
            [
                'menu_id' => 35,
                'menu_p_id' => '0',
                'menu_route_type_id' => '116',
                'menu_name' => 'Out Door',
                'menu_icon' => 'assets/images/out_door.png',
                'menu_status' => '1',
                'menu_sub_status' => '0',
                'menu_route' => '/OutDoorApprovalPage',
                'menu_group' => 'Approval',
                'menu_sequence' => '9',
                'menu_description' => null,
            ]
        ];

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('app_menus')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
