<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('employees', function (Blueprint $table) {
            $table->bigInteger('emp_id', true)->comment('employee\'s unique id');
            $table->integer('emp_status')->default(72)->comment('employee is active or not');
            $table->integer('emp_job_status')->nullable();
            $table->integer('emp_b_id')->nullable()->index('emp_b_id')->comment('employee\'s associated business\'s unique id');
            $table->integer('emp_br_id')->nullable()->index('emp_br_id')->comment('assign branch\'s unque id to the employee');
            $table->integer('emp_d_id')->nullable()->index('emp_d_id')->comment('employee\'s department id');
            $table->integer('emp_dg_id')->nullable()->index('emp_dg_id')->comment('employee\'s designation id');
            $table->integer('emp_role_id')->default(0)->index('emp_role_id')->comment('employee\'s assign role id');
            $table->integer('emp_grade_id')->nullable()->index('emp_grade_id')->comment('employee assign grade buy company \'s id');
            $table->integer('emp_dlr_id')->nullable();
            $table->bigInteger('emp_ssp_id')->nullable()->index('emp_ssp_id');
            $table->bigInteger('emp_pt_id')->nullable()->index('emp_pt_id');
            $table->bigInteger('emp_pb_id')->nullable()->index('emp_pb_id');
            $table->bigInteger('emp_pd_id')->nullable()->index('emp_pd_id');
            $table->integer('emp_pl_id')->nullable()->index('emp_pl_id')->comment('This represents the foreign key in the leave policy table.');
            $table->integer('emp_pwo_id')->nullable();
            $table->integer('emp_ap_id')->nullable()->index('emp_ap_id');
            $table->string('emp_email', 100)->nullable()->comment('employee\'s email id');
            $table->string('emp_phone', 20)->nullable()->comment('employee\'s mobile number');
            $table->string('emp_otp', 6)->nullable()->comment('otp');
            $table->string('emp_password')->nullable()->comment('password created by employee');
            $table->integer('emp_prefix')->nullable()->index('fh_employees_ibfk_36');
            $table->string('emp_fname', 20)->nullable()->comment('employee\'s first name');
            $table->string('emp_mname', 20)->nullable()->comment('employee\'s middle name');
            $table->string('emp_lname', 20)->nullable()->comment('employee\'s last name');
            $table->string('emp_full_name')->nullable();
            $table->text('emp_auth_token')->nullable()->comment('for firebase notification');
            $table->text('emp_bg_auth_token')->nullable();
            $table->text('emp_web_auth_token')->nullable();
            $table->bigInteger('emp_supervisor_id')->nullable();
            $table->string('emp_sap_budget_code', 100)->nullable();
            $table->string('emp_account_code', 100)->nullable();
            $table->string('emp_code', 20)->nullable();
            $table->integer('emp_cost_center')->nullable();
            $table->integer('emp_type_id')->nullable()->index('emp_type_id')->comment('employee\'s type contractual or regular');
            $table->boolean('emp_allow_joining_leave')->nullable()->default(false);
            $table->string('emp_joining_leave_calc_type', 50)->nullable();
            $table->integer('emp_joining_leave_before_date')->nullable()->default(0);
            $table->boolean('emp_allow_probation_leave')->nullable()->default(false);
            $table->integer('emp_contractual_type_id')->nullable()->index('emp_contractual_type_id')->comment('in contractual have different types like weekly, monthly etc id.');
            $table->text('emp_fcm_token')->nullable();
            $table->integer('emp_notice_period_shortfall_days')->nullable();
            $table->integer('emp_notice_period_day_for_employer')->nullable();
            $table->integer('emp_notice_period_day_for_employee')->nullable();
            $table->double('emp_vpf_percentage')->nullable();
            $table->string('emp_company_email', 100)->nullable()->comment('company\'s registered email id');
            $table->date('emp_dob')->nullable()->comment('employee\'s date of birth');
            $table->date('emp_probation_last_date')->nullable();
            $table->date('emp_date_of_joining')->nullable()->comment('employee\'s date of joining');
            $table->date('emp_group_date_of_joining')->nullable()->comment('employee\'s group joining date');
            $table->date('emp_date_of_gratuity')->nullable()->comment('gratuity date which is providing by company');
            $table->date('emp_date_of_transfer')->nullable()->comment('transfer date');
            $table->date('emp_date_of_expected_confirmation')->nullable()->comment('if employee selected then expected confirmation date proving by companty.');
            $table->date('emp_date_of_confirmation')->nullable()->comment('actual confirmation date for employee');
            $table->date('emp_date_of_pay_structure')->nullable();
            $table->integer('emp_probation_period')->nullable()->comment('probation period given by company to the employee.');
            $table->integer('emp_gender_id')->nullable()->index('emp_gender_id')->comment('employee\'s gender id like: male, female or other');
            $table->integer('emp_marital_status_id')->nullable()->index('emp_marital_status_id')->comment('employee\'s marital status like: married, unmarried, widower etc.');
            $table->integer('emp_cast_id')->nullable()->index('emp_cast_id')->comment('employee\'s cast id like: obc, general, sc or st.');
            $table->integer('emp_blood_group_id')->nullable()->index('emp_blood_group_id')->comment('blood group id');
            $table->integer('emp_gov_doc_type_id')->nullable()->index('emp_gov_doc_type_id')->comment('not in use in new form');
            $table->string('emp_gov_doc_type_number', 100)->nullable()->comment('not in use in new form');
            $table->string('emp_nationality', 100)->nullable()->comment('not in use in new form');
            $table->integer('emp_religion_id')->nullable()->index('emp_religion_id')->comment('not in use in new form');
            $table->text('emp_permanent_address')->nullable()->comment('not in use in new form');
            $table->boolean('emp_is_temporary_add_same')->nullable()->default(false);
            $table->string('emp_permanent_latitude', 20)->nullable();
            $table->string('emp_permanent_longitude', 20)->nullable();
            $table->string('emp_permanent_pin_code', 50)->nullable()->comment('not in use in new form');
            $table->text('emp_temporary_address')->nullable();
            $table->string('emp_temporary_longitude', 20)->nullable();
            $table->string('emp_temporary_latitude', 20)->nullable();
            $table->string('emp_temporary_pin_code', 50)->nullable()->comment('not in use in new form');
            $table->boolean('emp_is_geofencing_active')->nullable()->default(true);
            $table->boolean('emp_is_geowork_active')->nullable()->default(false);
            $table->json('emp_assign_geo_branch')->nullable();
            $table->boolean('emp_is_wifi_restricted')->nullable()->default(false);
            $table->boolean('emp_is_notification_enabled')->default(true);
            $table->integer('emp_shift_type_id')->nullable()->index('emp_shift_type_id')->comment('employee\'s assign shift\'s unique id.');
            $table->time('emp_assign_shift_start_time')->nullable()->comment('shift\'s start time');
            $table->time('emp_assign_shift_end_time')->nullable()->comment('shift\'s end time');
            $table->bigInteger('emp_reporting_manager_id')->nullable()->index('emp_reporting_manager_id')->comment('remporting manager\'s employee id');
            $table->bigInteger('approver_manager_1')->nullable();
            $table->bigInteger('approver_manager_2')->nullable();
            $table->string('emp_imei_no', 30)->nullable()->comment('employee\'s phone iemi number');
            $table->integer('emp_work_mode_id')->nullable()->index('emp_attendance_method_id')->comment('attendance method id like: office, wfh or outdoor');
            $table->string('emp_checkin_method_id')->nullable()->index('emp_checkin_method_id');
            $table->string('emp_bank_ifsc_code', 15)->nullable()->comment('bank branch ifsc code');
            $table->string('emp_bank_name')->nullable()->comment('bank name');
            $table->string('emp_bank_branch_name')->nullable()->comment('branch name');
            $table->string('emp_bank_account_no', 20)->nullable()->comment('bank account number');
            $table->string('emp_bank_branch_code', 10)->nullable()->comment('branch code');
            $table->string('emp_bank_micr_code', 15)->nullable()->comment('micr number of bank');
            $table->string('emp_bank_address_line1')->nullable()->comment('not in use in new form');
            $table->string('emp_bank_address_line2')->nullable()->comment('not in use in new form');
            $table->integer('emp_is_eps_enabled')->nullable();
            $table->string('emp_pan_number')->nullable();
            $table->string('emp_pan_file')->nullable();
            $table->string('emp_passport_number')->nullable();
            $table->string('emp_passport_file')->nullable();
            $table->string('emp_voter_id_number')->nullable();
            $table->string('emp_voter_id_file')->nullable();
            $table->string('emp_driving_license_number')->nullable();
            $table->string('emp_driving_license_file')->nullable();
            $table->string('emp_account_number')->nullable();
            $table->string('emp_passbook_file')->nullable();
            $table->string('emp_aadhar_number')->nullable();
            $table->string('emp_aadhar_file')->nullable();
            $table->boolean('emp_is_pf_enabled')->nullable()->default(false);
            $table->boolean('emp_is_tds_enabled')->nullable();
            $table->string('emp_pf_no', 30)->nullable()->comment('employee\'s pf number');
            $table->string('emp_pf_trust_code', 100)->nullable()->comment('pf truest code');
            $table->string('emp_pf_found_member')->nullable()->comment('member or not');
            $table->string('emp_pf_universal_ac_no', 20)->nullable()->comment('employee\' pf univasal account number');
            $table->date('emp_pf_joining_date')->nullable()->comment('pf joining date');
            $table->date('emp_pf_leaving_date')->nullable()->comment('pf leaving date');
            $table->mediumText('emp_pr_leaving_reason')->nullable()->comment('reason of leaving pf');
            $table->string('emp_pf_joining_no')->nullable();
            $table->string('emp_lwf_no')->nullable();
            $table->string('emp_eps_no')->nullable();
            $table->string('emp_esic_no', 20)->nullable();
            $table->date('emp_esic_joining_date')->nullable();
            $table->date('emp_esic_leaving_date')->nullable();
            $table->mediumText('emp_esic_leaving_reason')->nullable();
            $table->string('emp_group_insured_by')->nullable();
            $table->string('emp_group_insurance_no')->nullable();
            $table->date('emp_group_insurance_start_date')->nullable();
            $table->date('emp_group_insurance_till_date')->nullable();
            $table->string('emp_esic_dispensary')->nullable();
            $table->integer('emp_esic_limit')->nullable()->default(121);
            $table->string('emp_year_of_service')->nullable();
            $table->date('emp_retirement_date')->nullable();
            $table->date('emp_separation_submit_date')->nullable();
            $table->date('emp_expected_leaving_date')->nullable();
            $table->date('emp_leaving_date_as_per_notice_period')->nullable();
            $table->integer('emp_notice_period_req_days')->nullable();
            $table->mediumText('emp_leaving_reason')->nullable();
            $table->date('emp_leave_date')->nullable();
            $table->integer('emp_notice_period_serve_days')->nullable();
            $table->date('emp_settlement_from_date')->nullable();
            $table->date('emp_final_settlement_date')->nullable();
            $table->date('emp_exit_interview_date')->nullable();
            $table->date('emp_last_working_date')->nullable();
            $table->string('emp_paymentmode', 50)->nullable();
            $table->mediumText('emp_remark')->nullable();
            $table->string('emp_relative_name', 150)->nullable();
            $table->string('emp_relationship', 150)->nullable();
            $table->string('emp_relative_phone_no')->nullable();
            $table->string('emp_profile_photo')->nullable()->default('user.png');
            $table->string('emp_profile_s3_url')->nullable();
            $table->string('emp_rekognition_id')->nullable();
            $table->text('emp_documents_ref_file')->nullable();
            $table->timestamp('emp_otp_created_at')->nullable();
            $table->double('emp_tada_settlement_amt')->nullable();
            $table->integer('emp_attendance_preference')->default(367)->index();
            $table->integer('emp_category_id')->nullable();
            $table->boolean('is_super_admin')->nullable()->default(false);
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrentOnUpdate()->useCurrent();
            $table->string('emp_religion')->nullable();
            $table->string('emp_body_mark')->nullable();
            $table->string('emp_official_email')->nullable();
            $table->string('emp_official_contact')->nullable();
            $table->string('emp_emergency_contact')->nullable();
            $table->string('emp_emergency_relation')->nullable();
            $table->string('emp_salary_account_code')->nullable();
            $table->string('emp_salary_bank_ifsc_code')->nullable();
            $table->string('emp_salary_bank_name')->nullable();
            $table->string('emp_salary_bank_branch_name')->nullable();
            $table->string('emp_salary_bank_micr_code')->nullable();
            $table->string('emp_salary_bank_branch_code')->nullable();
            $table->string('emp_salary_bank_account_no')->nullable();
            $table->string('emp_profit_center')->nullable();
            $table->string('emp_region_id')->nullable();
            $table->text('emp_project_id')->nullable();
            $table->string('emp_accountpurpose', 100)->nullable();
            $table->date('emp_drivng_license_valid')->nullable();
            $table->date('emp_passport_valid')->nullable();
            $table->string('emp_google2fa_secret')->nullable();
            $table->timestamp('emp_google2fa_enabled_at')->nullable();
            $table->string('emp_assets_id')->nullable();
            $table->integer('emp_offline_status')->nullable()->default(0);
            $table->string('emp_sys_username')->nullable();
            $table->string('emp_sys_hostname')->nullable();
            $table->string('emp_sys_platform')->nullable();
            $table->string('emp_sys_model')->nullable();
            $table->string('emp_sys_uuid')->nullable();
            $table->string('emp_sys_macaddress')->nullable();
            $table->string('emp_last_seen_at')->nullable();
            $table->integer('emp_is_reminder_enabled')->nullable()->default(1);
            $table->tinyInteger('is_approval_manager')->nullable()->default(0);
            $table->tinyInteger('emp_is_whatsapp_enabled')->nullable()->default(0);
            $table->tinyInteger('emp_is_device_lock')->nullable()->default(0);
            $table->string('emp_device_token')->nullable();
            $table->tinyInteger('emp_is_device_restriction')->nullable()->default(0);
            $table->string('emp_device_id')->nullable();
            $table->integer('emp_remind_me_later')->nullable()->default(0);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('employees');
    }
};
